# Generated by Django 4.0.4 on 2022-04-15 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_specification', models.TextField(max_length=200)),
                ('desc_name_1', models.CharField(max_length=50)),
                ('desc_image_1', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail_1', models.TextField()),
                ('desc_name_2', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_image_2', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail_2', models.TextField(blank=True, null=True)),
                ('desc_name_3', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_image_3', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail_3', models.TextField(blank=True, null=True)),
                ('desc_name_4', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_image_4', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail_4', models.TextField(blank=True, null=True)),
                ('desc_name_5', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_image_5', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail_5', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_1', models.CharField(max_length=50)),
                ('weight_dimension_1', models.TextField()),
                ('display_1', models.TextField()),
                ('chip_1', models.TextField()),
                ('isight_cam1', models.TextField()),
                ('video_record1', models.TextField()),
                ('capacity_2', models.CharField(max_length=50)),
                ('weight_dimension_2', models.TextField()),
                ('display_2', models.TextField()),
                ('chip_2', models.TextField()),
                ('isight_cam2', models.TextField()),
                ('video_record2', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='main.product')),
                ('product_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
