# Generated by Django 4.0.4 on 2022-04-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_new_price_alter_product_off_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_specification', models.TextField(max_length=200)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='new')),
                ('product_newPrice', models.IntegerField(blank=True, null=True)),
                ('product_offPrice', models.IntegerField(blank=True, null=True)),
                ('desc_name', models.CharField(max_length=50)),
                ('desc_image', models.ImageField(blank=True, null=True, upload_to='new')),
                ('desc_detail', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
