# Generated by Django 4.0.4 on 2022-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdescription',
            old_name='desc_detail',
            new_name='desc_detail_1',
        ),
        migrations.RenameField(
            model_name='productdescription',
            old_name='desc_image',
            new_name='desc_image_1',
        ),
        migrations.RenameField(
            model_name='productdescription',
            old_name='product_image',
            new_name='desc_image_2',
        ),
        migrations.RenameField(
            model_name='productdescription',
            old_name='desc_name',
            new_name='desc_name_1',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='product_newPrice',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='product_offPrice',
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_detail_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_detail_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_detail_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_detail_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='new'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='new'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='new'),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_name_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_name_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_name_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='desc_name_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
