# Generated by Django 4.0.4 on 2022-04-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_review_rating_addcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='price',
        ),
        migrations.AddField(
            model_name='addcart',
            name='single_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addcart',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addcart',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
