# Generated by Django 4.0.4 on 2022-04-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_addcart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='total',
        ),
    ]
