# Generated by Django 4.0.4 on 2022-04-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_addcart_sub_total_remove_addcart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
